school/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'
urlpatterns = [
    path('', views.cabinet, name='cabinet'),
    path('booking_next_lesson/<int:lesson_id>', views.booking, name="booking_next_lesson"),
    path('cancel_booking_next_lesson/<int:booking_id>', views.cancel_booking, name="cancel_booking_next_lesson"),
    path('multi_booking/<int:lesson_id>', views.multi_booking, name="multi_booking"),
    path('events/', views.events, name="events"),
]

school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
]

school/booking/models.py
from datetime import date, datetime, timedelta, time

from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils import timezone

User = get_user_model()


def validate_schedule_week_days(value):
    if '1' not in value:
        raise ValidationError('Нет единиц в расписании на неделю')
    if value.count('0') + value.count('1') != len(value):
        raise ValidationError('В расписании на неделю есть символы кроме 0 и 1')
    if len(value) != 7:
        raise ValidationError('Длина расписания на неделю не равна 7')


class Lesson(models.Model):
    title = models.CharField('Название занятия', max_length=100, unique=True)
    description = models.TextField('Описание', null=True, blank=True)
    bootstrap_icon = models.CharField(
        'Иконка',
        max_length=50,
        default='bi-emoji-smile',
        help_text='https://icons.getbootstrap.com/icons/'
    )

    class Meta:
        ordering = ('title',)
        verbose_name = 'Занятие'
        verbose_name_plural = 'Занятия'

    def __str__(self):
        return self.title


class Event(Lesson):
    datetime_begin = models.DateTimeField('Время начала мероприятия')
    datetime_end = models.DateTimeField('Время завершения мероприятия')
    deadline_booking = models.DateTimeField('Время завершения бронирования')
    price = models.PositiveIntegerField('Стоимость')

    class Meta:
        ordering = ('-datetime_begin',)
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'
        constraints = [
            models.CheckConstraint(check=models.Q(datetime_begin__lt=models.F('datetime_end')), name='check_events_dates'),
            models.CheckConstraint(check=models.Q(deadline_booking__lt=models.F('datetime_begin')),
                                   name='check_events_deadlines'),
        ]

    def __str__(self):
        return self.title

    @property
    def is_deadline(self):
        return timezone.now() >= self.deadline_booking


class Schedule(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name='Занятие', on_delete=models.CASCADE, related_name='schedules')
    date_begin = models.DateField('Дата начала занятий')
    date_end = models.DateField('Дата завершения занятий')
    week_days = models.CharField('Дни проведения занятий', max_length=7, validators=[validate_schedule_week_days])

    class Meta:
        ordering = ('-date_begin', 'lesson')
        verbose_name = 'Расписание'
        verbose_name_plural = 'Расписания'
        constraints = [
            models.CheckConstraint(check=models.Q(date_begin__lt=models.F('date_end')), name='check_dates'),
        ]

    def __str__(self):
        return self.lesson.title

    def clean(self):
        if self.date_begin >= self.date_end:
            raise ValidationError('Дата начала занятий не может быть позже даты их завершения')

    @property
    def is_deadline(self):
        return datetime.now() >= self.deadline_time

    @property
    def next_lesson_day(self):
        if date.today() >= self.date_begin:
            evaluation_day = date.today()
        else:
            evaluation_day = self.date_begin

        weekday = evaluation_day.weekday()
        next_lesson_day = self.week_days.find('1', weekday + 1)
        next_lesson_delta = next_lesson_day - weekday
        if next_lesson_day == -1:
            next_lesson_day = self.week_days.find('1')
            next_lesson_delta = 7 - weekday + next_lesson_day
        next_lesson_date = evaluation_day + timedelta(days=next_lesson_delta)
        return next_lesson_date

    @property
    def is_next_lesson_tomorrow(self):
        return self.next_lesson_day - date.today() == timedelta(days=1)

    @property
    def deadline_time(self):
        day = self.next_lesson_day - timedelta(days=1)
        return datetime.combine(day, time(hour=settings.DEADLINE_TIME))

    @property
    def week_schedule(self):
        week_days = [
            'Понедельник',
            'Вторник',
            'Среда',
            'Четверг',
            'Пятница',
            'Суббота',
            'Воскресенье',
        ]
        return ', '.join([item[1].lower() for item in zip(self.week_days, week_days) if int(item[0])])

    @property
    def lesson_days(self):
        lessons = {}
        lesson_day = self.next_lesson_day
        if (self.next_lesson_day - date.today()).days == 1:
            if datetime.now().hour >= settings.DEADLINE_TIME:
                lesson_day += timedelta(days=1)
        week_schedule = [num for num, day in enumerate(self.week_days) if int(day)]
        while lesson_day < self.date_end:
            if lesson_day.weekday() in week_schedule:
                key = lesson_day.replace(year=lesson_day.year, day=1)
                if lessons.get(key):
                    lessons[key].append(lesson_day)
                else:
                    lessons[key] = [lesson_day]
            lesson_day += timedelta(days=1)
        return lessons


class Booking(models.Model):
    student = models.ForeignKey(User, verbose_name='Ученик', on_delete=models.CASCADE, related_name='bookings')
    lesson = models.ForeignKey(Schedule, verbose_name='Занятие', on_delete=models.CASCADE, related_name='bookings')
    date = models.DateField('День проведения занятия')

    class Meta:
        ordering = ('-date', 'lesson', 'student')
        verbose_name = 'Запись на занятие'
        verbose_name_plural = 'Записи на занятия'
        constraints = [
            models.UniqueConstraint(fields=('student', 'lesson', 'date'), name='unique_student_lesson_date'),
        ]

    def __str__(self):
        return '{0} {1} {2}'.format(self.date, self.lesson, self.student)


class EventBooking(models.Model):
    student = models.ForeignKey(User, verbose_name='Ученик', on_delete=models.CASCADE, related_name='event_bookings')
    event = models.ForeignKey(Event, verbose_name='Мероприятие', on_delete=models.CASCADE, related_name='event_bookings')

    class Meta:
        ordering = ('event', 'student')
        verbose_name = 'Запись на мероприятие'
        verbose_name_plural = 'Записи на мероприятия'
        constraints = [
            models.UniqueConstraint(fields=('student', 'event'), name='unique_student_event'),
        ]

    def __str__(self):
        return '{0} {1}'.format(self.event, self.student)

school/booking/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Booking, Schedule, Event, EventBooking
from datetime import date, timedelta
from django.utils import timezone
from django.conf import settings

@login_required
def cabinet(request):
    template = 'booking/cabinet.html'
    days_before = settings.ACCESS_BOOKING_DAYS_BEFORE_BEGIN_LESSONS
    schedule = Schedule.objects.filter(date_begin__lte=date.today() + timedelta(days=days_before), date_end__gt=date.today())
    booked = Booking.objects.filter(student=request.user).filter(date__gte=date.today()).all()
    bookings = {}
    for line in schedule:
        for booking in booked:
            if booking.lesson.lesson.id == line.lesson.id and booking.date == line.next_lesson_day:
                bookings[line.id] = booking.id
    context = {
        'schedule': schedule,
        'bookings': bookings,
    }
    return render(request, template, context)


@login_required
def events(request):
    template = 'booking/events.html'
    events = Event.objects.filter(datetime_begin__gt=timezone.now())
    booked = EventBooking.objects.filter(student=request.user).filter(event__in=events).values_list('event', flat=True)
    context = {
        'events': events,
        'booked': booked,
    }
    return render(request, template, context)


@login_required
def booking(request, lesson_id):
    lesson = get_object_or_404(Schedule, pk=lesson_id)
    Booking.objects.get_or_create(
        student=request.user,
        lesson=lesson,
        date=lesson.next_lesson_day,
    )
    template = 'booking/message.html'
    context = {
        'icon': 'bi-emoji-smile',
        'message': 'Вы успешно записались!',
        'lesson': lesson,
    }
    return render(request, template, context)


@login_required
def cancel_booking(request, booking_id):
    try:
        booking = Booking.objects.get(pk=booking_id)
    except:
        return redirect(reverse('booking:cabinet'))
    if booking.student == request.user:
        booking.delete()
    template = 'booking/message.html'
    context = {
        'icon': 'bi-emoji-smile-upside-down',
        'message': 'Вы успешно отписались!',
        'lesson': booking.lesson,
    }
    return render(request, template, context)


@login_required
def multi_booking(request, lesson_id):
    lesson = Schedule.objects.get(pk=lesson_id)
    booked = Booking.objects.filter(
        lesson=lesson_id,
        student=request.user,
        date__gte=date.today(),
    ).values_list('date', flat=True)
    if request.POST:
        post_booking = [
            date.fromisoformat(book_date) for book_date in request.POST.getlist('lesson_date')
        ]
        bookings = []
        for book_date in post_booking:
            bookings.append(
                Booking(
                    student=request.user,
                    lesson=lesson,
                    date=book_date,
                ),
            )
        Booking.objects.bulk_create(bookings, ignore_conflicts=True)
        Booking.objects.filter(
            lesson=lesson_id,
            student=request.user).exclude(
            date__in=post_booking,
        ).delete()


    template = 'booking/multi_booking.html'
    context = {
        'lesson': lesson,
        'booked': booked,
    }
    return render(request, template, context)

school/booking/templates/booking/cabinet.html
{% extends 'base.html' %}

{% block title %}
    1В: {{ user.get_full_name }}
{% endblock %}

{% block h1 %}
    {{ user.get_full_name }}
{% endblock %}

{% block content %}
{% load booking_extras %}
{% for line in schedule %}
<div class="card mb-3"">
  <div class="card-body">
    <h3 class="card-title">
        <i class="bi {{ line.lesson.bootstrap_icon }}"></i>
        {{ line.lesson.title }}
    </h3>
    <p class="card-text">
        Дни занятий: {{ line.week_schedule }}<br />
        {{ line.lesson.description }}</p>
      <ul class="list-group list-group-flush">
          <li class="list-group-item">
          Следующее занятие:
        {{ line.next_lesson_day|date:"l d.m.Y" }}
        {% if line.is_next_lesson_tomorrow %}
        (Завтра)
        {% endif %}

      {% if line.id in bookings %}
              <span class="badge bg-success rounded-pill"><i class="bi bi-check-circle"></i> ВЫ ЗАПИСАНЫ</span>
      {% else %}
              <span class="badge bg-secondary rounded-pill"><i class="bi bi-x-circle"></i> ВЫ НЕ ЗАПИСАНЫ</span>
      {% endif %}
              </p>
      <p style="background-color: {% if line.is_deadline %}LavenderBlush{% else %}Beige{% endif %};">
          Изменить запись можно {% if line.is_deadline %}было {% endif %}до:
          {% if line.is_next_lesson_tomorrow %}
          {{ line.deadline_time|date:"H:i d.m.Y" }} (Сегодня)
          {% else %}
          {{ line.deadline_time|date:"H:i d.m.Y (l)" }}
          {% endif %}
      </p>
      {% if line.id in bookings %}
              <a href="{% url 'booking:cancel_booking_next_lesson' bookings|hash:line.id %}" class="btn btn-outline-danger {% if line.is_deadline %}disabled{% endif %}"><i class="bi bi-x-circle"></i> Не пойдём на это занятие</a>
      {% else %}
              <a href="{% url 'booking:booking_next_lesson' line.id %}" class="btn btn-outline-success {% if line.is_deadline %}disabled{% endif %}"><i class="bi bi-check-circle"></i> Пойдём на это занятие</a>
      {% endif %}
              <a href="{% url 'booking:multi_booking' line.id %}" class="btn btn-outline-dark"><i class="bi bi-card-checklist"></i> Посмотреть запись на другие дни</a>
          </li>
      </ul>
  </div>
</div>
{% endfor %}
{% endblock %}

school/booking/templates/booking/events.html
{% extends 'base.html' %}

{% block title %}
    1В: {{ user.get_full_name }}
{% endblock %}

{% block h1 %}
    {{ user.get_full_name }}
{% endblock %}

{% block content %}
{% for event in events %}
<div class="card mb-3"">
  <div class="card-body">
    <h3 class="card-title">
        <i class="bi {{ event.bootstrap_icon }}"></i>
        {{ event.title }}
    </h3>
    <p class="card-text">
        {{ event.description }}</p>
      <ul class="list-group list-group-flush">
          <li class="list-group-item">
          Начало: {{ event.datetime_begin|date:"l d.m.Y H:i" }}


      {% if event.id in booked %}
              <span class="badge bg-success rounded-pill"><i class="bi bi-check-circle"></i> ВЫ ЗАПИСАНЫ</span>
      {% else %}
              <span class="badge bg-secondary rounded-pill"><i class="bi bi-x-circle"></i> ВЫ НЕ ЗАПИСАНЫ</span>
      {% endif %}
              <br />Завершение: {{ event.datetime_end|date:"l d.m.Y H:i" }}
              </p>
      <p style="background-color: {% if line.is_deadline %}LavenderBlush{% else %}Beige{% endif %};">
          Изменить запись можно {% if event.is_deadline %}было {% endif %}до:
          {{ event.deadline_booking|date:"H:i d.m.Y" }}
      </p>

      {% if event.id in booked %}
              <a href="{% url 'booking:cancel_booking_next_lesson' event.id %}" class="btn btn-outline-danger {% if event.is_deadline %}disabled{% endif %}"><i class="bi bi-x-circle"></i> Не пойдём на это мероприятие</a>
      {% else %}
              <a href="{% url 'booking:booking_next_lesson' event.id %}" class="btn btn-outline-success {% if event.is_deadline %}disabled{% endif %}"><i class="bi bi-check-circle"></i> Пойдём на это мероприятие</a>
      {% endif %}
          </li>
      </ul>
  </div>
</div>
{% endfor %}
{% endblock %}

school/booking/templates/booking/message.html
{% extends 'base.html' %}

{% block title %}
    1В: {{ user.get_full_name }}
{% endblock %}

{% block h1 %}
    {{ user.get_full_name }}
{% endblock %}

{% block content %}

<div class="card text-center">
  <div class="card-header">
    {{ message }}
  </div>
  <div class="card-body">
    <h1 class="card-title"><i class="bi {{ icon }}"></i></h1>
    <h3 class="card-title">{{ lesson.lesson.title }}</h3>
    <p class="card-text">
      {% if not permanent %}
        {{ lesson.next_lesson_day|date:"l d.m.Y" }}
        {% if line.is_next_lesson_tomorrow %}
        (Завтра)
        {% endif %}
        {% endif %}
      </p>
  </div>
  <div class="card-footer text-muted">
    <a href="{% url 'booking:cabinet' %}" class="btn btn-primary">На главную</a>
  </div>
</div>

{% endblock %}

school/booking/templates/booking/multi_booking.html
{% extends 'base.html' %}

{% block title %}
    1В: {{ user.get_full_name }}
{% endblock %}

{% block h1 %}
    {{ user.get_full_name }}
{% endblock %}

{% block content %}
<div class="card mb-3">

  <div class="card-body">
    <h3 class="card-title">
        <i class="bi {{ lesson.lesson.bootstrap_icon }}"></i>
        {{ lesson.lesson.title }}

    </h3>
    <p class="card-text">
        Дни занятий: {{ lesson.week_schedule }}<br />
        {{ lesson.lesson.description }}</p>
<div class="form-check mb-3">
  <input class="form-check-input" type="checkbox" value="" id="select_all" name="select_all" autocomplete="off" onclick="eventCheckBox()">
  <label class="form-check-label" for="select_all">
      <b>Групповое выделение</b>
  </label>
</div>

{% if lesson.lesson_days %}
      <form method="post" action="{% url 'booking:multi_booking' lesson.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary mb-3">Сохранить</button>
          <a href="{% url 'booking:cabinet' %}" class="btn btn-outline-primary mb-3">На главную</a>
{% for month, lessons in lesson.lesson_days.items %}
          <div class="mb-3">
          <h5>{{ month|date:"F Y" }}</h5>
          {% for lesson_date in lessons %}
<div class="form-check">
  <input class="form-check-input checkbox" type="checkbox" value='{{ lesson_date|date:"Y-m-d" }}' name='lesson_date' id='{{ lesson_date|date:"Y-m-d" }}' {% if lesson_date in booked %}checked{% endif %}>
  <label class="form-check-label" for='{{ lesson_date|date:"Y-m-d" }}'>
      {{lesson_date|date:"d.m.Y, l"}}
  </label>
</div>

{% endfor %}
              </div>
{% endfor %}
      </form>
{% endif %}

  </div>
</div>
{% endblock %}